"""Run once to populate the database with common polymers."""
from app.database import SessionLocal, engine
from app.models.material import Material
from app.database import Base

POLYMERS = [
    # ── Polyolefins ──────────────────────────────────────────────────────────
    dict(name="Polyethylene, Low Density", abbreviation="LDPE", category="thermoplastic",
         cas_number="9002-88-4", glass_transition_temp=-120, melting_temp=110, max_service_temp=80,
         min_service_temp=-60, tensile_strength=15, elongation_at_break=400, youngs_modulus=0.2,
         density=0.92, water_absorption=0.01, chemical_resistance="good", uv_resistance="poor",
         transparency="translucent", trade_names="Lupolen, Dowlex",
         manufacturers="LyondellBasell, Dow",
         typical_applications="Packaging films, bags, squeeze bottles, wire insulation"),

    dict(name="Polyethylene, High Density", abbreviation="HDPE", category="thermoplastic",
         cas_number="9002-88-4", glass_transition_temp=-120, melting_temp=130, max_service_temp=120,
         min_service_temp=-60, tensile_strength=30, elongation_at_break=800, youngs_modulus=1.0,
         density=0.95, water_absorption=0.01, chemical_resistance="good", uv_resistance="poor",
         transparency="opaque", trade_names="Rigidex, Hostalen",
         manufacturers="LyondellBasell, SABIC",
         typical_applications="Pipes, containers, toys, cutting boards, fuel tanks"),

    dict(name="Polypropylene", abbreviation="PP", category="thermoplastic",
         cas_number="9003-07-0", glass_transition_temp=-10, melting_temp=165, max_service_temp=130,
         min_service_temp=-20, tensile_strength=35, elongation_at_break=150, youngs_modulus=1.5,
         density=0.90, water_absorption=0.02, chemical_resistance="good", uv_resistance="poor",
         transparency="translucent", trade_names="Moplen, Metocene",
         manufacturers="LyondellBasell, Borealis",
         typical_applications="Automotive parts, packaging, medical devices, textiles"),

    # ── Styrenics ────────────────────────────────────────────────────────────
    dict(name="Polystyrene", abbreviation="PS", category="thermoplastic",
         cas_number="9003-53-6", glass_transition_temp=100, melting_temp=None, max_service_temp=70,
         min_service_temp=-20, tensile_strength=45, elongation_at_break=3, youngs_modulus=3.2,
         density=1.05, water_absorption=0.1, chemical_resistance="poor", uv_resistance="poor",
         transparency="transparent", trade_names="Styron, Lacqrene",
         manufacturers="Trinseo, INEOS",
         typical_applications="Disposable cups, packaging, CD cases, insulation"),

    dict(name="Acrylonitrile Butadiene Styrene", abbreviation="ABS", category="thermoplastic",
         cas_number="9003-56-9", glass_transition_temp=105, melting_temp=None, max_service_temp=80,
         min_service_temp=-20, tensile_strength=45, elongation_at_break=20, youngs_modulus=2.3,
         density=1.05, water_absorption=0.3, chemical_resistance="fair", uv_resistance="poor",
         transparency="opaque", trade_names="Terluran, Novodur",
         manufacturers="INEOS Styrolution, LG Chem",
         typical_applications="Electronics housings, automotive trim, LEGO bricks, appliances"),

    dict(name="Styrene Acrylonitrile", abbreviation="SAN", category="thermoplastic",
         cas_number="9003-54-7", glass_transition_temp=110, melting_temp=None, max_service_temp=85,
         min_service_temp=-20, tensile_strength=75, elongation_at_break=3, youngs_modulus=3.6,
         density=1.08, water_absorption=0.2, chemical_resistance="fair", uv_resistance="fair",
         transparency="transparent", trade_names="Lustran, Tyril",
         manufacturers="INEOS Styrolution, Lanxess",
         typical_applications="Kitchenware, cosmetic packaging, battery cases, instrument lenses"),

    # ── Vinyls ───────────────────────────────────────────────────────────────
    dict(name="Polyvinyl Chloride", abbreviation="PVC", category="thermoplastic",
         cas_number="9002-86-2", glass_transition_temp=80, melting_temp=None, max_service_temp=60,
         min_service_temp=-15, tensile_strength=55, elongation_at_break=40, youngs_modulus=3.0,
         density=1.40, water_absorption=0.1, chemical_resistance="good", uv_resistance="fair",
         transparency="transparent", trade_names="Vinnolit, Solvin",
         manufacturers="Mexichem, INEOS",
         typical_applications="Pipes, window profiles, cable insulation, flooring, medical tubing"),

    dict(name="Polyvinylidene Fluoride", abbreviation="PVDF", category="thermoplastic",
         cas_number="24937-79-9", glass_transition_temp=-40, melting_temp=170, max_service_temp=150,
         min_service_temp=-40, tensile_strength=50, elongation_at_break=300, youngs_modulus=2.0,
         density=1.78, water_absorption=0.04, chemical_resistance="excellent", uv_resistance="excellent",
         transparency="opaque", trade_names="Kynar, Solef",
         manufacturers="Arkema, Solvay",
         typical_applications="Chemical processing pipes, piezoelectric sensors, lithium battery binders"),

    # ── Acrylics ─────────────────────────────────────────────────────────────
    dict(name="Polymethyl Methacrylate", abbreviation="PMMA", category="thermoplastic",
         cas_number="9011-14-7", glass_transition_temp=105, melting_temp=None, max_service_temp=90,
         min_service_temp=-40, tensile_strength=75, elongation_at_break=5, youngs_modulus=3.3,
         density=1.19, water_absorption=0.3, refractive_index=1.49,
         chemical_resistance="poor", uv_resistance="excellent",
         transparency="transparent", trade_names="Plexiglas, Lucite, Perspex",
         manufacturers="Röhm, Mitsubishi Chemical",
         typical_applications="Glazing, displays, lenses, medical implants, signage"),

    # ── Polyamides ───────────────────────────────────────────────────────────
    dict(name="Polyamide 6", abbreviation="PA6", category="thermoplastic",
         cas_number="25038-54-4", glass_transition_temp=50, melting_temp=220, max_service_temp=120,
         min_service_temp=-40, tensile_strength=80, elongation_at_break=150, youngs_modulus=2.8,
         density=1.13, water_absorption=2.7, chemical_resistance="good", uv_resistance="poor",
         transparency="opaque", trade_names="Ultramid B, Akulon",
         manufacturers="BASF, DSM",
         typical_applications="Gears, bearings, cable ties, textile fibers, food packaging"),

    dict(name="Polyamide 66", abbreviation="PA66", category="thermoplastic",
         cas_number="32131-17-2", glass_transition_temp=70, melting_temp=260, max_service_temp=130,
         min_service_temp=-40, tensile_strength=85, elongation_at_break=60, youngs_modulus=3.3,
         density=1.14, water_absorption=2.5, chemical_resistance="good", uv_resistance="poor",
         transparency="opaque", trade_names="Zytel, Ultramid A",
         manufacturers="DuPont, BASF",
         typical_applications="Automotive connectors, electrical components, sports equipment, toothbrush bristles"),

    dict(name="Polyamide 12", abbreviation="PA12", category="thermoplastic",
         cas_number="25038-74-8", glass_transition_temp=37, melting_temp=178, max_service_temp=100,
         min_service_temp=-60, tensile_strength=55, elongation_at_break=300, youngs_modulus=1.6,
         density=1.02, water_absorption=0.25, chemical_resistance="good", uv_resistance="fair",
         transparency="translucent", trade_names="Vestamid, Rilsan",
         manufacturers="Evonik, Arkema",
         typical_applications="Fuel lines, brake tubing, powder coatings, flexible packaging"),

    # ── Polyesters ───────────────────────────────────────────────────────────
    dict(name="Polyethylene Terephthalate", abbreviation="PET", category="thermoplastic",
         cas_number="25038-59-9", glass_transition_temp=75, melting_temp=255, max_service_temp=120,
         min_service_temp=-60, tensile_strength=80, elongation_at_break=30, youngs_modulus=3.1,
         density=1.38, water_absorption=0.1, refractive_index=1.57,
         chemical_resistance="good", uv_resistance="fair",
         transparency="transparent", trade_names="Arnite, Rynite",
         manufacturers="DSM, DuPont",
         typical_applications="Beverage bottles, food packaging, polyester fibers, capacitor films"),

    dict(name="Polybutylene Terephthalate", abbreviation="PBT", category="thermoplastic",
         cas_number="26062-94-2", glass_transition_temp=50, melting_temp=225, max_service_temp=130,
         min_service_temp=-40, tensile_strength=60, elongation_at_break=50, youngs_modulus=2.7,
         density=1.31, water_absorption=0.08, chemical_resistance="good", uv_resistance="fair",
         transparency="opaque", trade_names="Valox, Celanex",
         manufacturers="SABIC, Celanese",
         typical_applications="Automotive connectors, electrical housings, switches"),

    dict(name="Polycarbonate", abbreviation="PC", category="thermoplastic",
         cas_number="25037-45-0", glass_transition_temp=147, melting_temp=None, max_service_temp=130,
         min_service_temp=-40, tensile_strength=65, elongation_at_break=100, youngs_modulus=2.4,
         density=1.20, water_absorption=0.15, refractive_index=1.58,
         chemical_resistance="fair", uv_resistance="fair",
         transparency="transparent", trade_names="Makrolon, Lexan",
         manufacturers="Covestro, SABIC",
         typical_applications="Automotive glazing, safety helmets, optical discs, medical devices"),

    # ── High-performance ─────────────────────────────────────────────────────
    dict(name="Polyether Ether Ketone", abbreviation="PEEK", category="thermoplastic",
         cas_number="31694-16-3", glass_transition_temp=143, melting_temp=343, max_service_temp=250,
         min_service_temp=-60, tensile_strength=100, elongation_at_break=35, youngs_modulus=3.7,
         flexural_modulus=4.1, density=1.32, water_absorption=0.1,
         chemical_resistance="excellent", uv_resistance="good", flame_retardancy="V-0",
         transparency="opaque", trade_names="Victrex PEEK, Ketaspire",
         manufacturers="Victrex, Solvay",
         typical_applications="Aerospace components, medical implants, semiconductor equipment, bearings"),

    dict(name="Polyphenylene Sulfide", abbreviation="PPS", category="thermoplastic",
         cas_number="26125-40-6", glass_transition_temp=85, melting_temp=280, max_service_temp=220,
         min_service_temp=-60, tensile_strength=75, elongation_at_break=3, youngs_modulus=3.8,
         density=1.35, water_absorption=0.02, chemical_resistance="excellent", uv_resistance="good",
         flame_retardancy="V-0", transparency="opaque", trade_names="Ryton, Fortron",
         manufacturers="Solvay, Celanese",
         typical_applications="Automotive under-hood, electrical connectors, chemical pumps"),

    dict(name="Polyetherimide", abbreviation="PEI", category="thermoplastic",
         cas_number="61128-46-9", glass_transition_temp=217, melting_temp=None, max_service_temp=170,
         min_service_temp=-40, tensile_strength=105, elongation_at_break=7, youngs_modulus=3.3,
         density=1.27, water_absorption=0.25, chemical_resistance="good", uv_resistance="fair",
         flame_retardancy="V-0", transparency="transparent", trade_names="Ultem",
         manufacturers="SABIC",
         typical_applications="Aircraft interiors, medical sterilizable instruments, microwave cookware"),

    dict(name="Polysulfone", abbreviation="PSU", category="thermoplastic",
         cas_number="25135-51-7", glass_transition_temp=186, melting_temp=None, max_service_temp=160,
         min_service_temp=-60, tensile_strength=70, elongation_at_break=50, youngs_modulus=2.5,
         density=1.24, water_absorption=0.3, chemical_resistance="good", uv_resistance="poor",
         transparency="transparent", trade_names="Udel, Ultrason S",
         manufacturers="Solvay, BASF",
         typical_applications="Membrane filtration, medical devices, hot water fittings"),

    dict(name="Polyethersulfone", abbreviation="PES", category="thermoplastic",
         cas_number="25667-42-9", glass_transition_temp=230, melting_temp=None, max_service_temp=180,
         min_service_temp=-60, tensile_strength=85, elongation_at_break=40, youngs_modulus=2.6,
         density=1.37, water_absorption=0.43, chemical_resistance="good", uv_resistance="poor",
         transparency="transparent", trade_names="Ultrason E, Radel A",
         manufacturers="BASF, Solvay",
         typical_applications="Filtration membranes, medical devices, food processing equipment"),

    # ── Fluoropolymers ───────────────────────────────────────────────────────
    dict(name="Polytetrafluoroethylene", abbreviation="PTFE", category="thermoplastic",
         cas_number="9002-84-0", glass_transition_temp=-73, melting_temp=327, max_service_temp=260,
         min_service_temp=-200, tensile_strength=30, elongation_at_break=400, youngs_modulus=0.5,
         density=2.20, water_absorption=0.01, chemical_resistance="excellent", uv_resistance="excellent",
         flame_retardancy="V-0", transparency="opaque", trade_names="Teflon, Algoflon",
         manufacturers="Chemours, Daikin",
         typical_applications="Non-stick coatings, seals, gaskets, chemical-resistant linings, bearings"),

    dict(name="Fluorinated Ethylene Propylene", abbreviation="FEP", category="thermoplastic",
         cas_number="25067-11-2", glass_transition_temp=-150, melting_temp=260, max_service_temp=200,
         min_service_temp=-200, tensile_strength=25, elongation_at_break=300, youngs_modulus=0.5,
         density=2.15, water_absorption=0.01, chemical_resistance="excellent", uv_resistance="excellent",
         transparency="transparent", trade_names="Teflon FEP",
         manufacturers="Chemours, Daikin",
         typical_applications="Wire insulation, chemical tubing, labware coatings"),

    # ── Polyurethanes / thermosets ────────────────────────────────────────────
    dict(name="Thermoplastic Polyurethane", abbreviation="TPU", category="thermoplastic elastomer",
         cas_number="9009-54-5", glass_transition_temp=-40, melting_temp=180, max_service_temp=100,
         min_service_temp=-40, tensile_strength=50, elongation_at_break=500, youngs_modulus=0.05,
         density=1.20, water_absorption=0.7, chemical_resistance="fair", uv_resistance="fair",
         transparency="transparent", trade_names="Elastollan, Desmopan",
         manufacturers="BASF, Covestro",
         typical_applications="Phone cases, shoe soles, hoses, seals, medical tubing"),

    dict(name="Epoxy Resin", abbreviation="EP", category="thermoset",
         cas_number="25068-38-6", glass_transition_temp=120, melting_temp=None, max_service_temp=130,
         min_service_temp=-40, tensile_strength=85, elongation_at_break=4, youngs_modulus=3.5,
         density=1.20, water_absorption=0.15, chemical_resistance="good", uv_resistance="poor",
         flame_retardancy="HB", transparency="transparent", trade_names="Araldite, D.E.R.",
         manufacturers="Huntsman, Olin",
         typical_applications="Structural adhesives, composite matrices, PCB laminates, coatings"),

    dict(name="Unsaturated Polyester Resin", abbreviation="UP", category="thermoset",
         glass_transition_temp=80, melting_temp=None, max_service_temp=100,
         tensile_strength=65, elongation_at_break=2, youngs_modulus=3.5,
         density=1.20, water_absorption=0.2, chemical_resistance="fair", uv_resistance="poor",
         transparency="translucent", trade_names="Palatal, Norsodyne",
         manufacturers="Aliancys, AOC",
         typical_applications="Boat hulls, automotive body panels, bathtubs, wind turbine blades"),

    # ── Elastomers ───────────────────────────────────────────────────────────
    dict(name="Styrene-Butadiene Rubber", abbreviation="SBR", category="elastomer",
         cas_number="9003-55-8", glass_transition_temp=-55, melting_temp=None, max_service_temp=100,
         min_service_temp=-50, tensile_strength=20, elongation_at_break=500,
         density=0.94, water_absorption=0.1, chemical_resistance="fair", uv_resistance="poor",
         transparency="opaque", trade_names="Buna, Solprene",
         manufacturers="Lanxess, Trinseo",
         typical_applications="Car tires, shoe soles, conveyor belts, gaskets"),

    dict(name="Ethylene Propylene Diene Monomer", abbreviation="EPDM", category="elastomer",
         cas_number="25038-36-2", glass_transition_temp=-60, melting_temp=None, max_service_temp=150,
         min_service_temp=-50, tensile_strength=15, elongation_at_break=400,
         density=0.87, water_absorption=0.1, chemical_resistance="good", uv_resistance="excellent",
         transparency="opaque", trade_names="Nordel, Keltan",
         manufacturers="Dow, Lanxess",
         typical_applications="Automotive weatherstripping, roofing membranes, garden hoses"),

    dict(name="Silicone Rubber", abbreviation="VMQ", category="elastomer",
         glass_transition_temp=-123, melting_temp=None, max_service_temp=250,
         min_service_temp=-60, tensile_strength=10, elongation_at_break=600,
         density=1.10, water_absorption=0.1, chemical_resistance="good", uv_resistance="excellent",
         transparency="translucent", trade_names="Silastic, Silopren",
         manufacturers="Dow, Momentive",
         typical_applications="Medical devices, baking molds, electrical insulation, gaskets"),

    dict(name="Natural Rubber", abbreviation="NR", category="elastomer",
         cas_number="9006-04-6", glass_transition_temp=-70, melting_temp=None, max_service_temp=80,
         min_service_temp=-50, tensile_strength=30, elongation_at_break=800,
         density=0.93, water_absorption=0.2, chemical_resistance="poor", uv_resistance="poor",
         transparency="opaque", trade_names="SMR, RSS",
         manufacturers="Various",
         typical_applications="Tires, gloves, elastic bands, vibration dampers"),

    # ── Specialty / bio-based ─────────────────────────────────────────────────
    dict(name="Polylactic Acid", abbreviation="PLA", category="biopolymer",
         cas_number="26100-51-6", glass_transition_temp=60, melting_temp=175, max_service_temp=55,
         min_service_temp=-20, tensile_strength=60, elongation_at_break=6, youngs_modulus=3.5,
         density=1.24, water_absorption=0.5, chemical_resistance="poor", uv_resistance="fair",
         transparency="transparent", trade_names="Ingeo, Luminy",
         manufacturers="NatureWorks, Total Corbion",
         typical_applications="3D printing filament, food packaging, disposable cutlery, biomedical implants"),

    dict(name="Polyhydroxyalkanoate", abbreviation="PHA", category="biopolymer",
         glass_transition_temp=5, melting_temp=175, max_service_temp=100,
         tensile_strength=40, elongation_at_break=6, youngs_modulus=3.5,
         density=1.25, water_absorption=0.5, chemical_resistance="fair", uv_resistance="fair",
         transparency="opaque", trade_names="Mirel, Kaneka PHBH",
         manufacturers="Danimer Scientific, Kaneka",
         typical_applications="Biodegradable packaging, agricultural films, disposables"),

    dict(name="Polyoxymethylene", abbreviation="POM", category="thermoplastic",
         cas_number="9002-81-7", glass_transition_temp=-60, melting_temp=165, max_service_temp=100,
         min_service_temp=-40, tensile_strength=70, elongation_at_break=35, youngs_modulus=3.1,
         density=1.41, water_absorption=0.22, chemical_resistance="good", uv_resistance="poor",
         transparency="opaque", trade_names="Delrin, Hostaform",
         manufacturers="DuPont, Celanese",
         typical_applications="Precision gears, bearings, fasteners, fuel system components"),

    dict(name="Polytetramethylene Ether Glycol", abbreviation="PTMEG", category="thermoplastic elastomer",
         glass_transition_temp=-80, melting_temp=30, max_service_temp=80,
         tensile_strength=25, elongation_at_break=700,
         density=0.98, water_absorption=0.3,
         transparency="transparent", trade_names="Terathane, PolyTHF",
         manufacturers="Invista, BASF",
         typical_applications="Spandex fibers, TPU raw material, cast elastomers"),

    dict(name="Ethylene Vinyl Acetate", abbreviation="EVA", category="thermoplastic elastomer",
         cas_number="24937-78-8", glass_transition_temp=-35, melting_temp=75, max_service_temp=60,
         min_service_temp=-40, tensile_strength=18, elongation_at_break=750,
         density=0.95, water_absorption=0.1, chemical_resistance="fair", uv_resistance="fair",
         transparency="transparent", trade_names="Elvax, Evatane",
         manufacturers="DuPont, Arkema",
         typical_applications="Foam shoe soles, hot-melt adhesives, solar cell encapsulants, flexible packaging"),

    dict(name="Polyimide", abbreviation="PI", category="thermoplastic",
         glass_transition_temp=360, melting_temp=None, max_service_temp=300,
         min_service_temp=-200, tensile_strength=170, elongation_at_break=7, youngs_modulus=3.1,
         density=1.43, water_absorption=2.8, chemical_resistance="excellent", uv_resistance="fair",
         flame_retardancy="V-0", transparency="opaque", trade_names="Kapton, Vespel",
         manufacturers="DuPont, UBE",
         typical_applications="Flexible PCBs, aerospace thermal insulation, semiconductor packaging"),

    dict(name="Polyphenylene Oxide", abbreviation="PPO", category="thermoplastic",
         glass_transition_temp=210, melting_temp=None, max_service_temp=120,
         min_service_temp=-40, tensile_strength=55, elongation_at_break=25, youngs_modulus=2.5,
         density=1.06, water_absorption=0.07, chemical_resistance="fair", uv_resistance="poor",
         transparency="opaque", trade_names="Noryl, Luranyl",
         manufacturers="SABIC, BASF",
         typical_applications="Automotive interiors, electrical enclosures, water meters"),

    dict(name="Liquid Crystal Polymer", abbreviation="LCP", category="thermoplastic",
         glass_transition_temp=None, melting_temp=350, max_service_temp=240,
         tensile_strength=180, elongation_at_break=2, youngs_modulus=10.0,
         density=1.40, water_absorption=0.02, chemical_resistance="excellent", uv_resistance="good",
         flame_retardancy="V-0", transparency="opaque", trade_names="Vectra, Xydar",
         manufacturers="Celanese, Solvay",
         typical_applications="Miniature electrical connectors, microwave cookware, fiber optic components"),

    dict(name="Polyvinyl Alcohol", abbreviation="PVA", category="thermoplastic",
         cas_number="9002-89-5", glass_transition_temp=85, melting_temp=200, max_service_temp=80,
         tensile_strength=70, elongation_at_break=200,
         density=1.30, water_absorption=200.0, chemical_resistance="poor", uv_resistance="fair",
         transparency="transparent", trade_names="Mowiol, Elvanol",
         manufacturers="Kuraray, Sekisui",
         typical_applications="Water-soluble packaging, adhesives, textile sizing, 3D printing support material"),

    dict(name="Chlorinated Polyvinyl Chloride", abbreviation="CPVC", category="thermoplastic",
         glass_transition_temp=115, melting_temp=None, max_service_temp=95,
         tensile_strength=58, elongation_at_break=5, youngs_modulus=3.4,
         density=1.56, water_absorption=0.04, chemical_resistance="good", uv_resistance="fair",
         transparency="opaque", trade_names="Flowguard, Corzan",
         manufacturers="Lubrizol",
         typical_applications="Hot water pipes, industrial chemical handling pipes, fire sprinkler systems"),

    dict(name="Polyaryletherketon", abbreviation="PAEK", category="thermoplastic",
         glass_transition_temp=156, melting_temp=373, max_service_temp=260,
         tensile_strength=110, elongation_at_break=30, youngs_modulus=4.2,
         density=1.30, water_absorption=0.1, chemical_resistance="excellent", uv_resistance="good",
         flame_retardancy="V-0", transparency="opaque", trade_names="Kepstan, AvaSpire",
         manufacturers="Solvay, Arkema",
         typical_applications="Aerospace structural parts, medical instruments, oil and gas seals"),

    dict(name="Cellulose Acetate", abbreviation="CA", category="biopolymer",
         cas_number="9004-35-7", glass_transition_temp=190, melting_temp=None, max_service_temp=60,
         tensile_strength=55, elongation_at_break=30, youngs_modulus=1.8,
         density=1.30, water_absorption=2.5, chemical_resistance="poor", uv_resistance="fair",
         transparency="transparent", trade_names="Tenite, Bioceta",
         manufacturers="Eastman, Daicel",
         typical_applications="Eyeglass frames, tool handles, photographic film base, cigarette filters"),

    dict(name="Polyvinyl Butyral", abbreviation="PVB", category="thermoplastic",
         glass_transition_temp=70, melting_temp=None, max_service_temp=70,
         tensile_strength=20, elongation_at_break=300,
         density=1.07, water_absorption=1.0, refractive_index=1.48,
         chemical_resistance="fair", uv_resistance="fair",
         transparency="transparent", trade_names="Butvar, Mowital",
         manufacturers="Eastman, Kuraray",
         typical_applications="Laminated safety glass (automotive windshields), photovoltaic module encapsulants"),

    dict(name="Nylon 11", abbreviation="PA11", category="thermoplastic",
         cas_number="25035-04-5", glass_transition_temp=42, melting_temp=185, max_service_temp=100,
         min_service_temp=-60, tensile_strength=55, elongation_at_break=300, youngs_modulus=1.6,
         density=1.04, water_absorption=0.9, chemical_resistance="good", uv_resistance="fair",
         transparency="opaque", trade_names="Rilsan B",
         manufacturers="Arkema",
         typical_applications="Automotive fuel lines, powder coatings, offshore flexible pipes"),

    dict(name="High Impact Polystyrene", abbreviation="HIPS", category="thermoplastic",
         glass_transition_temp=90, melting_temp=None, max_service_temp=70,
         tensile_strength=30, elongation_at_break=45, youngs_modulus=2.1,
         density=1.04, water_absorption=0.1, chemical_resistance="poor", uv_resistance="poor",
         transparency="opaque", trade_names="Polystyrol, Styrolux",
         manufacturers="INEOS, LG Chem",
         typical_applications="Refrigerator liners, yogurt containers, toys, 3D printing filament"),

    dict(name="Polyisoprene", abbreviation="IR", category="elastomer",
         glass_transition_temp=-70, melting_temp=None, max_service_temp=80,
         tensile_strength=25, elongation_at_break=700,
         density=0.91, water_absorption=0.1, chemical_resistance="poor", uv_resistance="poor",
         transparency="opaque", trade_names="Natsyn, Cariflex",
         manufacturers="Goodyear, Kraton",
         typical_applications="Medical gloves, baby bottle nipples, adhesives, vibration mounts"),

    dict(name="Nitrile Rubber", abbreviation="NBR", category="elastomer",
         glass_transition_temp=-35, melting_temp=None, max_service_temp=120,
         min_service_temp=-40, tensile_strength=25, elongation_at_break=400,
         density=1.00, water_absorption=0.4, chemical_resistance="excellent", uv_resistance="poor",
         transparency="opaque", trade_names="Perbunan, Krynac",
         manufacturers="Lanxess, Zeon",
         typical_applications="Oil-resistant seals and gaskets, fuel hoses, gloves"),

    dict(name="Polychloroprene", abbreviation="CR", category="elastomer",
         cas_number="9010-98-4", glass_transition_temp=-43, melting_temp=None, max_service_temp=120,
         min_service_temp=-40, tensile_strength=25, elongation_at_break=500,
         density=1.23, water_absorption=0.3, chemical_resistance="good", uv_resistance="good",
         transparency="opaque", trade_names="Neoprene, Baypren",
         manufacturers="DuPont, Lanxess",
         typical_applications="Wetsuits, cable jacketing, industrial belts, adhesives"),

    dict(name="Styrene Block Copolymer", abbreviation="SBS", category="thermoplastic elastomer",
         glass_transition_temp=-90, melting_temp=None, max_service_temp=80,
         tensile_strength=30, elongation_at_break=800,
         density=0.94, water_absorption=0.1, chemical_resistance="poor", uv_resistance="poor",
         transparency="translucent", trade_names="Kraton D, Styroflex",
         manufacturers="Kraton, INEOS",
         typical_applications="Shoe soles, adhesives, asphalt modification, soft-touch grips"),

    dict(name="Styrene Ethylene Butylene Styrene", abbreviation="SEBS", category="thermoplastic elastomer",
         glass_transition_temp=-60, melting_temp=None, max_service_temp=120,
         tensile_strength=20, elongation_at_break=700,
         density=0.90, water_absorption=0.01, chemical_resistance="good", uv_resistance="good",
         transparency="translucent", trade_names="Kraton G, Tuftec",
         manufacturers="Kraton, Asahi Kasei",
         typical_applications="Medical devices, overmolding, wire insulation, baby products"),

    dict(name="Phenol Formaldehyde Resin", abbreviation="PF", category="thermoset",
         glass_transition_temp=300, melting_temp=None, max_service_temp=200,
         tensile_strength=60, elongation_at_break=1, youngs_modulus=7.0,
         density=1.30, water_absorption=0.3, chemical_resistance="good", uv_resistance="poor",
         flame_retardancy="V-0", transparency="opaque", trade_names="Bakelite, Durite",
         manufacturers="Hexion, Sumitomo Bakelite",
         typical_applications="Electrical outlets, brake pads, circuit board laminates, billiard balls"),

    dict(name="Melamine Formaldehyde Resin", abbreviation="MF", category="thermoset",
         glass_transition_temp=300, melting_temp=None, max_service_temp=130,
         tensile_strength=70, elongation_at_break=1, youngs_modulus=9.0,
         density=1.50, water_absorption=0.5, chemical_resistance="good", uv_resistance="good",
         flame_retardancy="V-0", transparency="opaque", trade_names="Formica, Cymel",
         manufacturers="Allnex, Ineos Melamines",
         typical_applications="Tableware, laminates for furniture, surface coatings, adhesives"),

    dict(name="Polyacetal Copolymer", abbreviation="POM-C", category="thermoplastic",
         glass_transition_temp=-60, melting_temp=163, max_service_temp=90,
         tensile_strength=62, elongation_at_break=40, youngs_modulus=2.7,
         density=1.41, water_absorption=0.20, chemical_resistance="good", uv_resistance="poor",
         transparency="opaque", trade_names="Hostaform C, Ultraform",
         manufacturers="Celanese, BASF",
         typical_applications="Valve bodies, pump parts, precision mechanical components"),

    dict(name="Polyethylene Naphthalate", abbreviation="PEN", category="thermoplastic",
         glass_transition_temp=120, melting_temp=265, max_service_temp=155,
         tensile_strength=200, elongation_at_break=70, youngs_modulus=5.0,
         density=1.36, water_absorption=0.5, chemical_resistance="good", uv_resistance="excellent",
         transparency="transparent", trade_names="Teonex",
         manufacturers="Teijin",
         typical_applications="High-barrier food packaging, flexible electronics, capacitor films"),
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(Material).count() > 0:
            print("Database already seeded. Skipping.")
            return
        for data in POLYMERS:
            db.add(Material(**data))
        db.commit()
        print(f"Seeded {len(POLYMERS)} polymers.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
